### ISSUE TITLE
Volume JSON files don't have URL to download them

### ISSUE THREAD

**Issue by Twinklebear** [pavolzetor/open_scivis_datasets#1]
It seems like they should have the URL in the JSON as well. It might seem a bit redundant but since the JSON file provides metadata for the files on the webpage, but I think it'd be handy to have. Instead of going to the webpage and then finding the volume I can just copy the url from the JSON and wget it instead.

**Comment by pavolzetor** [comment]
The file path is good idea (also relates checksum to a file) and since there is only one mirror absolute URL is fine. Fixed in fb7beb6ce33778711519d0e3c65d533a8055ad6c.
